/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { inject } from ".././injection";

/**
 * @summary Root
 */
export type rootGetResponse200 = {
  data: unknown;
  status: 200;
};

export type rootGetResponseSuccess = rootGetResponse200 & {
  headers: Headers;
};
export type rootGetResponse = rootGetResponseSuccess;

export const getRootGetUrl = () => {
  return `/`;
};

export const rootGet = async (
  options?: RequestInit,
): Promise<rootGetResponse> => {
  return inject<rootGetResponse>(getRootGetUrl(), {
    ...options,
    method: "GET",
  });
};
