version: '3'  

tasks:
  build:
    desc: "Build the docker compose environment"
    cmds:
      - docker-compose build
      
  run-local:
    desc: "Run local docker compose environment"
    cmds:
      - docker-compose up

  test:
    desc: "Run tests against the server"
    dir: src/simple_discord/tests
    env:
      API_URL: "http://localhost:8000"
      API_PATH: "/api/v1"
    cmds:
      - pytest -m integration

  test-stress:
    desc: "Run stress tests against the server"
    dir: src/simple_discord/tests
    env:
      API_URL: "http://localhost:8000"
      API_PATH: "/api/v1"
    cmds:
      - pytest -m stress -s -v
  
