version: '3'  

tasks:
  default:
    silent: true
    cmds:
      - task --list
        
  build:
    desc: "Build the docker compose environment"
    cmds:
      - docker compose build

  run:local:
    desc: "Run local docker compose in a simple development environment"
    cmds:
      - docker compose up

  run:local:sim:
    desc: "Run local docker compose environment mirroring production setup"
    cmds:
      - docker compose -f docker-compose.yaml -f infra/local/docker-compose.yaml up

  clean:local:
    desc: "Stop and remove local docker compose environment"
    cmds:
      - docker compose down --volumes --remove-orphans

  test:integration:
    desc: "Run tests against the server"
    dir: backend/src/harmony/tests
    env:
      API_ENDPOINT: http://localhost:8000
    cmds:
      - pytest -m integration

  test:stress:
    desc: "Run stress tests against the server"
    dir: backend/src/harmony/tests
    env:
      API_ENDPOINT: http://localhost:8000
    cmds:
      - pytest -m stress -s -v
  
  openapi:extract:
    desc: "Extract OpenAPI schema from FastAPI and save to frontend"
    cmds:
      - python backend/specs/extract_openapi.py > frontend/openapi.json

  openapi:generate:
    desc: "Generate API client from OpenAPI schema using Orval"
    dir: frontend
    cmds:
      - npx orval