/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChatMessage } from "./chatMessage";

export interface ChatHistoryResponse {
  messages: ChatMessage[];
}
