/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ChatCreateRequest {
  /**
   * @minItems 1
   * @maxItems 10
   */
  user_id_list: string[];
}
