/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ChatMessage {
  chat_id: string;
  ulid: string;
  timestamp: string;
  user_id: string;
  content: string;
}
