/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  ChatCreateRequest,
  ChatCreatedResponse,
  ChatHistoryResponse,
  ChatMessage,
  HTTPValidationError,
  MessageSendRequest,
} from ".././model";

import { inject } from ".././injection";

/**
 * Creates a new chat room between the current user and a list of target users.

- **user_id_list**: A list of user_ids for the users to include.
- **Constraints**: 
    - Max 10 users per chat (initially, you can add more later).
    - You cannot create a chat with non-existent users.
    - The creator is automatically added to the chat.
 * @summary Create a new chat
 */
export type createChatApiV1ChatsPostResponse201 = {
  data: ChatCreatedResponse;
  status: 201;
};

export type createChatApiV1ChatsPostResponse400 = {
  data: void;
  status: 400;
};

export type createChatApiV1ChatsPostResponse401 = {
  data: void;
  status: 401;
};

export type createChatApiV1ChatsPostResponse404 = {
  data: void;
  status: 404;
};

export type createChatApiV1ChatsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createChatApiV1ChatsPostResponseSuccess =
  createChatApiV1ChatsPostResponse201 & {
    headers: Headers;
  };
export type createChatApiV1ChatsPostResponseError = (
  | createChatApiV1ChatsPostResponse400
  | createChatApiV1ChatsPostResponse401
  | createChatApiV1ChatsPostResponse404
  | createChatApiV1ChatsPostResponse422
) & {
  headers: Headers;
};

export type createChatApiV1ChatsPostResponse =
  | createChatApiV1ChatsPostResponseSuccess
  | createChatApiV1ChatsPostResponseError;

export const getCreateChatApiV1ChatsPostUrl = () => {
  return `/api/v1/chats/`;
};

export const createChatApiV1ChatsPost = async (
  chatCreateRequest: ChatCreateRequest,
  options?: RequestInit,
): Promise<createChatApiV1ChatsPostResponse> => {
  return inject<createChatApiV1ChatsPostResponse>(
    getCreateChatApiV1ChatsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(chatCreateRequest),
    },
  );
};

/**
 * Persist a message to the database for a specific chat.

Returns the message details including the generated ULID and timestamp.
 * @summary Send a message
 */
export type sendMessageApiV1ChatsChatIdPostResponse201 = {
  data: ChatMessage;
  status: 201;
};

export type sendMessageApiV1ChatsChatIdPostResponse401 = {
  data: void;
  status: 401;
};

export type sendMessageApiV1ChatsChatIdPostResponse403 = {
  data: void;
  status: 403;
};

export type sendMessageApiV1ChatsChatIdPostResponse404 = {
  data: void;
  status: 404;
};

export type sendMessageApiV1ChatsChatIdPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type sendMessageApiV1ChatsChatIdPostResponseSuccess =
  sendMessageApiV1ChatsChatIdPostResponse201 & {
    headers: Headers;
  };
export type sendMessageApiV1ChatsChatIdPostResponseError = (
  | sendMessageApiV1ChatsChatIdPostResponse401
  | sendMessageApiV1ChatsChatIdPostResponse403
  | sendMessageApiV1ChatsChatIdPostResponse404
  | sendMessageApiV1ChatsChatIdPostResponse422
) & {
  headers: Headers;
};

export type sendMessageApiV1ChatsChatIdPostResponse =
  | sendMessageApiV1ChatsChatIdPostResponseSuccess
  | sendMessageApiV1ChatsChatIdPostResponseError;

export const getSendMessageApiV1ChatsChatIdPostUrl = (chatId: string) => {
  return `/api/v1/chats/${chatId}`;
};

export const sendMessageApiV1ChatsChatIdPost = async (
  chatId: string,
  messageSendRequest: MessageSendRequest,
  options?: RequestInit,
): Promise<sendMessageApiV1ChatsChatIdPostResponse> => {
  return inject<sendMessageApiV1ChatsChatIdPostResponse>(
    getSendMessageApiV1ChatsChatIdPostUrl(chatId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(messageSendRequest),
    },
  );
};

/**
 * Retrieves all messages for a specific chat. Messages are sorted by ULID (chronologically).
 * @summary Get chat history
 */
export type getChatHistoryApiV1ChatsChatIdGetResponse200 = {
  data: ChatHistoryResponse;
  status: 200;
};

export type getChatHistoryApiV1ChatsChatIdGetResponse401 = {
  data: void;
  status: 401;
};

export type getChatHistoryApiV1ChatsChatIdGetResponse403 = {
  data: void;
  status: 403;
};

export type getChatHistoryApiV1ChatsChatIdGetResponse404 = {
  data: void;
  status: 404;
};

export type getChatHistoryApiV1ChatsChatIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getChatHistoryApiV1ChatsChatIdGetResponseSuccess =
  getChatHistoryApiV1ChatsChatIdGetResponse200 & {
    headers: Headers;
  };
export type getChatHistoryApiV1ChatsChatIdGetResponseError = (
  | getChatHistoryApiV1ChatsChatIdGetResponse401
  | getChatHistoryApiV1ChatsChatIdGetResponse403
  | getChatHistoryApiV1ChatsChatIdGetResponse404
  | getChatHistoryApiV1ChatsChatIdGetResponse422
) & {
  headers: Headers;
};

export type getChatHistoryApiV1ChatsChatIdGetResponse =
  | getChatHistoryApiV1ChatsChatIdGetResponseSuccess
  | getChatHistoryApiV1ChatsChatIdGetResponseError;

export const getGetChatHistoryApiV1ChatsChatIdGetUrl = (chatId: string) => {
  return `/api/v1/chats/${chatId}`;
};

export const getChatHistoryApiV1ChatsChatIdGet = async (
  chatId: string,
  options?: RequestInit,
): Promise<getChatHistoryApiV1ChatsChatIdGetResponse> => {
  return inject<getChatHistoryApiV1ChatsChatIdGetResponse>(
    getGetChatHistoryApiV1ChatsChatIdGetUrl(chatId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * **Hard deletes** a chat and all its associated history.

- This operation performs a 'soft' check immediately.
- The actual deletion of thousands of messages happens in a **Background Task** 
  to prevent the API from hanging.
 * @summary Delete a chat
 */
export type deleteChatApiV1ChatsChatIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteChatApiV1ChatsChatIdDeleteResponse401 = {
  data: void;
  status: 401;
};

export type deleteChatApiV1ChatsChatIdDeleteResponse403 = {
  data: void;
  status: 403;
};

export type deleteChatApiV1ChatsChatIdDeleteResponse404 = {
  data: void;
  status: 404;
};

export type deleteChatApiV1ChatsChatIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteChatApiV1ChatsChatIdDeleteResponseSuccess =
  deleteChatApiV1ChatsChatIdDeleteResponse204 & {
    headers: Headers;
  };
export type deleteChatApiV1ChatsChatIdDeleteResponseError = (
  | deleteChatApiV1ChatsChatIdDeleteResponse401
  | deleteChatApiV1ChatsChatIdDeleteResponse403
  | deleteChatApiV1ChatsChatIdDeleteResponse404
  | deleteChatApiV1ChatsChatIdDeleteResponse422
) & {
  headers: Headers;
};

export type deleteChatApiV1ChatsChatIdDeleteResponse =
  | deleteChatApiV1ChatsChatIdDeleteResponseSuccess
  | deleteChatApiV1ChatsChatIdDeleteResponseError;

export const getDeleteChatApiV1ChatsChatIdDeleteUrl = (chatId: string) => {
  return `/api/v1/chats/${chatId}`;
};

export const deleteChatApiV1ChatsChatIdDelete = async (
  chatId: string,
  options?: RequestInit,
): Promise<deleteChatApiV1ChatsChatIdDeleteResponse> => {
  return inject<deleteChatApiV1ChatsChatIdDeleteResponse>(
    getDeleteChatApiV1ChatsChatIdDeleteUrl(chatId),
    {
      ...options,
      method: "DELETE",
    },
  );
};
