/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  HTTPValidationError,
  UserChatsResponse,
  UserCreateRequest,
  UserResponse,
} from ".././model";

import { inject } from ".././injection";

/**
 * Registers a new user in the system.

- **Validation**: Checks if the email is unique.
- **Security**: The password is securely hashed (Argon2) before storage.
- **Output**: Returns the generated User ID (ULID).
 * @summary Register a new user
 */
export type signUpApiV1UsersPostResponse201 = {
  data: UserResponse;
  status: 201;
};

export type signUpApiV1UsersPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type signUpApiV1UsersPostResponseSuccess =
  signUpApiV1UsersPostResponse201 & {
    headers: Headers;
  };
export type signUpApiV1UsersPostResponseError =
  signUpApiV1UsersPostResponse422 & {
    headers: Headers;
  };

export type signUpApiV1UsersPostResponse =
  | signUpApiV1UsersPostResponseSuccess
  | signUpApiV1UsersPostResponseError;

export const getSignUpApiV1UsersPostUrl = () => {
  return `/api/v1/users/`;
};

export const signUpApiV1UsersPost = async (
  userCreateRequest: UserCreateRequest,
  options?: RequestInit,
): Promise<signUpApiV1UsersPostResponse> => {
  return inject<signUpApiV1UsersPostResponse>(getSignUpApiV1UsersPostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userCreateRequest),
  });
};

/**
 * Retrieves a list of Chat IDs that the currently logged-in user participates in.
 * @summary Get my chats
 */
export type getMyChatsApiV1UsersMeChatsGetResponse200 = {
  data: UserChatsResponse;
  status: 200;
};

export type getMyChatsApiV1UsersMeChatsGetResponse401 = {
  data: void;
  status: 401;
};

export type getMyChatsApiV1UsersMeChatsGetResponseSuccess =
  getMyChatsApiV1UsersMeChatsGetResponse200 & {
    headers: Headers;
  };
export type getMyChatsApiV1UsersMeChatsGetResponseError =
  getMyChatsApiV1UsersMeChatsGetResponse401 & {
    headers: Headers;
  };

export type getMyChatsApiV1UsersMeChatsGetResponse =
  | getMyChatsApiV1UsersMeChatsGetResponseSuccess
  | getMyChatsApiV1UsersMeChatsGetResponseError;

export const getGetMyChatsApiV1UsersMeChatsGetUrl = () => {
  return `/api/v1/users/me/chats`;
};

export const getMyChatsApiV1UsersMeChatsGet = async (
  options?: RequestInit,
): Promise<getMyChatsApiV1UsersMeChatsGetResponse> => {
  return inject<getMyChatsApiV1UsersMeChatsGetResponse>(
    getGetMyChatsApiV1UsersMeChatsGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * **Soft delete** the current user.

- Marks the user as 'tombstoned' in the database.
- The user will no longer be able to log in.
- Historical data (messages) is preserved for data integrity.
 * @summary Deactivate my account
 */
export type deleteMeApiV1UsersMeDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteMeApiV1UsersMeDeleteResponse401 = {
  data: void;
  status: 401;
};

export type deleteMeApiV1UsersMeDeleteResponseSuccess =
  deleteMeApiV1UsersMeDeleteResponse204 & {
    headers: Headers;
  };
export type deleteMeApiV1UsersMeDeleteResponseError =
  deleteMeApiV1UsersMeDeleteResponse401 & {
    headers: Headers;
  };

export type deleteMeApiV1UsersMeDeleteResponse =
  | deleteMeApiV1UsersMeDeleteResponseSuccess
  | deleteMeApiV1UsersMeDeleteResponseError;

export const getDeleteMeApiV1UsersMeDeleteUrl = () => {
  return `/api/v1/users/me`;
};

export const deleteMeApiV1UsersMeDelete = async (
  options?: RequestInit,
): Promise<deleteMeApiV1UsersMeDeleteResponse> => {
  return inject<deleteMeApiV1UsersMeDeleteResponse>(
    getDeleteMeApiV1UsersMeDeleteUrl(),
    {
      ...options,
      method: "DELETE",
    },
  );
};
