/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  BodyLoginApiV1AuthTokenPost,
  HTTPValidationError,
  Token,
} from ".././model";

import { inject } from ".././injection";

/**
 * **OAuth2 compatible token login.**

This endpoint exchanges user credentials for a JWT Access Token.

- **username**: Must contain the user's **Email Address**.
- **password**: The plain-text password.

Returns a Bearer token to be used in the `Authorization` header for subsequent requests.
 * @summary Login / Get Access Token
 */
export type loginApiV1AuthTokenPostResponse200 = {
  data: Token;
  status: 200;
};

export type loginApiV1AuthTokenPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type loginApiV1AuthTokenPostResponseSuccess =
  loginApiV1AuthTokenPostResponse200 & {
    headers: Headers;
  };
export type loginApiV1AuthTokenPostResponseError =
  loginApiV1AuthTokenPostResponse422 & {
    headers: Headers;
  };

export type loginApiV1AuthTokenPostResponse =
  | loginApiV1AuthTokenPostResponseSuccess
  | loginApiV1AuthTokenPostResponseError;

export const getLoginApiV1AuthTokenPostUrl = () => {
  return `/api/v1/auth/token`;
};

export const loginApiV1AuthTokenPost = async (
  bodyLoginApiV1AuthTokenPost: BodyLoginApiV1AuthTokenPost,
  options?: RequestInit,
): Promise<loginApiV1AuthTokenPostResponse> => {
  const formUrlEncoded = new URLSearchParams();
  if (
    bodyLoginApiV1AuthTokenPost.grant_type !== undefined &&
    bodyLoginApiV1AuthTokenPost.grant_type !== null
  ) {
    formUrlEncoded.append(`grant_type`, bodyLoginApiV1AuthTokenPost.grant_type);
  }
  formUrlEncoded.append(`username`, bodyLoginApiV1AuthTokenPost.username);
  formUrlEncoded.append(`password`, bodyLoginApiV1AuthTokenPost.password);
  if (bodyLoginApiV1AuthTokenPost.scope !== undefined) {
    formUrlEncoded.append(`scope`, bodyLoginApiV1AuthTokenPost.scope);
  }
  if (
    bodyLoginApiV1AuthTokenPost.client_id !== undefined &&
    bodyLoginApiV1AuthTokenPost.client_id !== null
  ) {
    formUrlEncoded.append(`client_id`, bodyLoginApiV1AuthTokenPost.client_id);
  }
  if (
    bodyLoginApiV1AuthTokenPost.client_secret !== undefined &&
    bodyLoginApiV1AuthTokenPost.client_secret !== null
  ) {
    formUrlEncoded.append(
      `client_secret`,
      bodyLoginApiV1AuthTokenPost.client_secret,
    );
  }

  return inject<loginApiV1AuthTokenPostResponse>(
    getLoginApiV1AuthTokenPostUrl(),
    {
      ...options,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options?.headers,
      },
      body: formUrlEncoded,
    },
  );
};
